"""Neutral filler text. Each theme is six singular subjects and six predicates that fit any of them.

A sentence is "The <subject> <predicate>." and a processing block is two sentences of one theme.
Themes are split by use and never shared between splits: name calibration, development,
the matched-history evaluation, and the reversal episodes.
"""

THEMES = {
    "stockroom": (["carton", "shelf label", "packing list", "hand truck", "tape roll", "storage bin"],
                  ["is kept near the back door", "was counted on Tuesday", "sits on the lower rack",
                   "belongs to the second aisle", "was moved after lunch", "is listed in the ledger"]),
    "post_office": (["parcel", "stamp sheet", "mail cart", "sorting tray", "address form", "counter scale"],
                    ["is stored behind the counter", "was checked this morning", "rests beside the window",
                     "is used every weekday", "was placed on the table", "is marked with a number"]),
    "library_desk": (["catalog card", "return cart", "reading lamp", "date stamp", "book sleeve", "desk calendar"],
                     ["is kept at the front desk", "was sorted by a clerk", "stands near the stairs",
                      "is replaced each spring", "was filed under history", "is shared by two rooms"]),
    "bus_depot": (["timetable", "route map", "ticket roll", "depot gate", "fuel gauge", "spare mirror"],
                  ["is posted by the entrance", "was printed last month", "hangs above the bench",
                   "is checked before departure", "was updated in March", "is visible from the road"]),
    "kitchen_shelf": (["measuring cup", "bread board", "spice jar", "dish rack", "paper towel", "oven timer"],
                      ["is kept on the top shelf", "was rinsed after breakfast", "sits beside the kettle",
                       "is used for baking", "was bought at the market", "is stored in a drawer"]),
    "garden_shed": (["watering can", "seed packet", "garden hose", "clay pot", "hand rake", "plant label"],
                    ["is stored under the bench", "was filled on Monday", "leans against the fence",
                     "is used in early spring", "was left by the gate", "is kept out of the rain"]),
    "office_supplies": (["stapler", "file folder", "desk tray", "printer cable", "note pad", "paper clip"],
                        ["is kept in the top drawer", "was ordered in bulk", "sits next to the monitor",
                         "is shared across the team", "was labeled with a marker", "is restocked every month"]),
    "train_platform": (["platform sign", "waiting bench", "signal lamp", "luggage cart", "clock face",
                        "ticket gate"],
                       ["is located at the north end", "was painted two years ago", "faces the main track",
                        "is inspected every week", "was installed by the city", "is lit after sunset"]),
    "laundry_room": (["laundry basket", "drying rack", "soap dispenser", "ironing board", "lint filter",
                      "folding table"],
                     ["is kept near the sink", "was wiped down on Friday", "stands by the window",
                      "is used twice a week", "was set against the wall", "is stored in the closet"]),
    "map_room": (["wall map", "survey chart", "compass rose", "scale bar", "grid index", "contour line"],
                 ["is drawn in blue ink", "was revised last year", "appears in the lower corner",
                  "is printed on heavy paper", "was copied from an atlas", "is aligned with the border"]),
    "bicycle_shop": (["tire pump", "spoke wrench", "chain guard", "bell lever", "seat post", "brake cable"],
                     ["is hung on the pegboard", "was adjusted yesterday", "rests on the workbench",
                      "is sold in two sizes", "was shipped from the factory", "is priced on a tag"]),
    "school_hallway": (["notice board", "coat hook", "floor mat", "trophy case", "water fountain",
                        "class schedule"],
                       ["is mounted beside the door", "was cleaned over the weekend", "runs along the east wall",
                        "is checked by the staff", "was added in the fall", "is visible from the stairs"]),
    "weather_station": (["rain gauge", "wind vane", "data logger", "sensor mast", "solar panel", "field notebook"],
                        ["is read at noon", "was calibrated in April", "stands on the hilltop",
                         "is recorded every hour", "was mounted on a pole", "is covered by a shield"]),
    "bakery_counter": (["bread basket", "price card", "cake stand", "paper bag", "flour bin", "cooling rack"],
                       ["is placed by the register", "was filled before opening", "sits under the glass",
                        "is refilled each morning", "was stacked on the shelf", "is wiped at closing"]),
    "harbor_office": (["tide table", "mooring log", "harbor chart", "radio set", "dock ladder", "signal flag"],
                      ["is kept in the front office", "was updated at dawn", "hangs near the pier door",
                       "is used by the pilots", "was stored for the winter", "is checked on arrival"]),
    "paint_store": (["color chart", "paint tray", "mixing stick", "drop cloth", "roller frame", "sample card"],
                    ["is displayed near the aisle", "was restocked on Thursday", "lies on the lower shelf",
                     "is sold by the dozen", "was sorted by shade", "is wrapped in plain paper"]),
    "clock_repair": (["brass gear", "watch band", "spring bar", "glass cover", "winding key", "parts tray"],
                     ["is kept under the lamp", "was measured with calipers", "sits in a small box",
                      "is ordered from a supplier", "was polished last week", "is labeled by size"]),
    "farm_stand": (["egg carton", "produce crate", "chalk sign", "cash box", "hanging scale", "shade canopy"],
                   ["is set up by the road", "was loaded at sunrise", "rests on the wooden table",
                    "is used through the summer", "was carried from the barn", "is packed away at dusk"]),
    "print_shop": (["ink drum", "paper reel", "proof sheet", "cutting mat", "type case", "press lever"],
                   ["is stored beside the press", "was checked for alignment", "sits on the long counter",
                    "is replaced after each run", "was delivered on a pallet", "is covered overnight"]),
    "museum_storage": (["display case", "specimen drawer", "gallery label", "loan form", "packing crate",
                        "index card"],
                       ["is housed on the lower floor", "was cataloged in June", "stands behind the partition",
                        "is handled with gloves", "was photographed for the record", "is numbered in pencil"]),
    "hotel_lobby": (["room key", "guest ledger", "luggage rack", "brochure stand", "desk bell", "floor plan"],
                    ["is kept at reception", "was arranged by the porter", "stands near the elevator",
                     "is updated each evening", "was placed by the entrance", "is printed in two languages"]),
    "hardware_aisle": (["hinge set", "drill bit", "sanding block", "wall anchor", "tape measure", "pipe fitting"],
                       ["is shelved in aisle nine", "was tagged with a barcode", "hangs from a metal hook",
                        "is sold in packs of four", "was moved to the end cap", "is listed in the catalog"]),
    "aquarium_room": (["water filter", "feeding chart", "glass tank", "air pump", "gravel tray", "light hood"],
                      ["is cleaned every Sunday", "was installed by a technician", "sits against the far wall",
                       "is set on a timer", "was rinsed in the basin", "is checked for leaks"]),
    "tailor_shop": (["thread spool", "pattern sheet", "fabric bolt", "pin cushion", "chalk wheel", "dress form"],
                    ["is kept on the cutting table", "was measured twice", "stands beside the mirror",
                     "is arranged by color", "was ordered from a mill", "is stored on the top rack"]),
    "parking_garage": (["ticket machine", "level marker", "exit ramp", "speed sign", "pay station",
                        "ceiling light"],
                       ["is found on the second level", "was repainted in August", "faces the south stairwell",
                        "is serviced every quarter", "was numbered by the owner", "is shown on the diagram"]),
    "pottery_studio": (["glaze bucket", "kiln shelf", "trimming tool", "clay bag", "banding wheel", "test tile"],
                       ["is stored near the kiln", "was weighed on the scale", "dries on the wire rack",
                        "is mixed once a month", "was stamped with a date", "is wrapped in plastic"]),
    "ferry_terminal": (["boarding ramp", "fare chart", "queue rail", "deck plan", "life ring", "gate bell"],
                       ["is lowered before boarding", "was posted by the agent", "runs beside the ticket hall",
                        "is tested every season", "was fixed to the railing", "is marked in yellow paint"]),
    "stationery_shop": (["ink bottle", "envelope box", "ruler set", "sketch pad", "pencil case", "ribbon spool"],
                        ["is displayed in the window", "was unpacked on Wednesday", "lies in the glass cabinet",
                         "is sold with a receipt", "was arranged by height", "is stocked near the till"]),
    "surveyor_van": (["tripod leg", "range pole", "field map", "marker stake", "level vial", "chain bag"],
                     ["is packed in the rear", "was used on the north lot", "lies under the side bench",
                      "is carried to each site", "was cleaned after the job", "is tagged with a serial number"]),
    "cafeteria_line": (["tray stack", "napkin holder", "soup ladle", "menu board", "salad bowl", "coin dish"],
                       ["is set out before noon", "was washed in the back", "sits at the end of the line",
                        "is refilled by the staff", "was moved closer to the door", "is cleared after service"]),
    "telephone_exchange": (["patch cord", "relay rack", "call register", "fuse panel", "test handset",
                            "wiring chart"],
                           ["is mounted in the main frame", "was logged by the operator", "hangs on the side panel",
                            "is inspected once a year", "was traced to the third row", "is labeled in white ink"]),
    "seed_catalog": (["order form", "price table", "planting guide", "zone chart", "index page", "photo plate"],
                     ["is printed near the back", "was mailed in January", "appears on the inside cover",
                      "is arranged by season", "was set in small type", "is folded into the binding"]),
    "boat_shed": (["oar rack", "hull stand", "rope coil", "varnish tin", "canvas cover", "keel block"],
                  ["is stored along the side wall", "was brushed down last week", "sits above the slipway",
                   "is used when the tide is low", "was tied with a plain knot", "is kept dry under a tarp"]),
    "record_archive": (["box file", "shelf marker", "index ledger", "microfilm reel", "request slip",
                        "transfer list"],
                       ["is held on the third floor", "was entered by an archivist", "stands in the end bay",
                        "is retrieved on request", "was boxed in acid-free card", "is dated on the spine"]),
    "sports_locker": (["score sheet", "cone stack", "ball pump", "whistle cord", "line marker", "kit bag"],
                      ["is kept in the end locker", "was counted after practice", "lies on the top shelf",
                       "is signed out by the coach", "was returned on Saturday", "is stored with the nets"]),
    "lighthouse_log": (["lamp lens", "fuel record", "stair rail", "fog signal", "watch book", "gallery door"],
                       ["is cleaned before dusk", "was noted in the log", "faces the open channel",
                        "is tested at the start of each shift", "was painted grey", "is reached by the upper stair"]),
    "flower_stall": (["ribbon roll", "water bucket", "wrapping sheet", "price stick", "display tier",
                      "order pad"],
                     ["is set out on the pavement", "was trimmed at the bench", "stands under the awning",
                      "is refreshed at midday", "was tied with green string", "is packed into the van"]),
    "chemistry_bench": (["glass funnel", "ring stand", "wash bottle", "sample vial", "balance pan",
                         "label tape"],
                        ["is rinsed with distilled water", "was weighed to the milligram", "sits inside the hood",
                         "is returned to the rack", "was dated by the student", "is stored at room temperature"]),
    "camping_store": (["tent pole", "ground sheet", "fuel canister", "trail map", "lantern hook", "stuff sack"],
                      ["is shelved near the entrance", "was tested in the yard", "hangs on the display wall",
                       "is rented by the day", "was folded into thirds", "is tagged with a weight"]),
    "courier_van": (["delivery slip", "cargo strap", "route sheet", "door latch", "parcel shelf", "scanner dock"],
                    ["is checked at each stop", "was loaded in stop order", "sits behind the driver seat",
                     "is signed by the customer", "was fastened before leaving", "is emptied at the depot"]),
    "piano_workshop": (["tuning fork", "felt strip", "key cover", "pedal rod", "string gauge", "bench cushion"],
                       ["is kept in the tool roll", "was fitted on Thursday", "lies across the open lid",
                        "is measured in millimeters", "was replaced during service", "is stored in a flat case"]),
    "town_hall": (["meeting agenda", "seating chart", "record book", "notice frame", "podium lamp", "visitor log"],
                  ["is posted in the corridor", "was approved at the last session", "rests on the clerk's desk",
                   "is archived every December", "was printed on letterhead", "is open during office hours"]),
    "optician_desk": (["lens cloth", "frame tray", "eye chart", "case rack", "screw kit", "fitting mirror"],
                      ["is placed near the chair", "was restocked by the assistant", "hangs at reading height",
                       "is cleaned between visits", "was sorted by width", "is lit from above"]),
    "grain_elevator": (["weigh ticket", "loading spout", "bin gauge", "dust screen", "belt drive",
                        "sample probe"],
                       ["is read at the scale house", "was serviced before harvest", "runs above the pit",
                        "is logged for each truck", "was greased in the spring", "is numbered on the side"]),
    "toy_shelf": (["puzzle box", "block set", "spinning top", "paint set", "card deck", "wooden train"],
                  ["is stacked on the middle shelf", "was priced on Monday", "sits beside the register",
                   "is sold with a small bag", "was shelved by age group", "is wrapped on request"]),
    "dental_office": (["appointment card", "supply cart", "rinse cup", "chart folder", "bib clip", "waiting chair"],
                      ["is kept at the front window", "was restocked before nine", "stands in room two",
                       "is filed by last name", "was wiped with a cloth", "is replaced for each visit"]),
    "brick_yard": (["pallet wrap", "kiln car", "clay chute", "stack marker", "loading bay", "mold frame"],
                   ["is parked beside the dryer", "was counted at the gate", "stands along the rear fence",
                    "is moved by forklift", "was sprayed with water", "is numbered for each batch"]),
    "radio_studio": (["cue sheet", "mixing desk", "cable reel", "studio clock", "script stand", "level meter"],
                     ["is set before the broadcast", "was checked by the engineer", "sits to the left of the door",
                      "is reset at the top of the hour", "was wired to the rack", "is dimmed during recording"]),
    "cheese_cellar": (["aging rack", "brine tub", "wheel label", "cellar thermometer", "cutting wire",
                       "wax pot"],
                      ["is turned every few days", "was brought down in crates", "rests on a wooden plank",
                       "is checked for humidity", "was dated with a stamp", "is kept at a steady temperature"]),
    "auction_house": (["lot tag", "bid paddle", "sale catalog", "viewing table", "packing slip", "display easel"],
                      ["is numbered for the sale", "was entered in the register", "stands near the rostrum",
                       "is collected after payment", "was photographed in the hall", "is listed by category"]),
    "shoe_repair": (["heel block", "sole sheet", "lace box", "polish tin", "stitching awl", "claim ticket"],
                    ["is kept under the counter", "was trimmed to size", "hangs on the rear wall",
                     "is matched by number", "was glued and clamped", "is ready by Friday"]),
    "planetarium": (["star chart", "dome projector", "seat row", "show schedule", "pointer lamp", "sky globe"],
                    ["is dimmed before the show", "was aligned with the horizon", "stands at the center",
                     "is printed for each season", "was serviced in the winter", "is labeled with constellations"]),
    "ice_rink": (["skate rack", "rink barrier", "rental form", "score clock", "rubber mat", "resurfacer key"],
                 ["is checked before each session", "was replaced over the summer", "runs along the boards",
                  "is returned at the desk", "was marked with tape", "is stored in the side room"]),
    "vineyard_shed": (["picking bin", "trellis wire", "pruning log", "row marker", "press basket", "barrel tag"],
                      ["is stacked at the row end", "was tightened in February", "hangs inside the shed door",
                       "is rinsed after use", "was filled by the crew", "is written in chalk"]),
    "locksmith_van": (["key blank", "pin kit", "cutting wheel", "door gauge", "cylinder tray", "job sheet"],
                      ["is sorted by profile", "was cut at the curb", "sits in the side drawer",
                       "is billed by the hour", "was matched to the sample", "is kept in a steel box"]),
    "carpet_store": (["sample book", "roll stand", "edge trim", "floor plan sketch", "measuring wheel",
                      "delivery note"],
                     ["is laid out near the window", "was cut to length", "leans by the stock room",
                      "is priced by the square meter", "was rolled and taped", "is signed at handover"]),
    "observatory": (["dome shutter", "finder scope", "log sheet", "filter wheel", "drive motor", "red lamp"],
                    ["is opened after dark", "was aligned on a bright star", "sits on the north pier",
                     "is recorded for each exposure", "was balanced with a weight", "is covered at dawn"]),
    "canal_lock": (["gate paddle", "winding handle", "depth board", "mooring ring", "lock ladder",
                    "keeper's notice"],
                   ["is raised to fill the chamber", "was oiled last month", "stands on the towpath side",
                    "is used by passing boats", "was set into the stone", "is painted black and white"]),
    "sewing_class": (["bobbin case", "seam guide", "practice cloth", "needle pack", "thread chart",
                      "pattern envelope"],
                     ["is handed out at the start", "was pressed flat", "sits at each station",
                      "is collected at the end", "was cut along the fold", "is pinned to the board"]),
    "tool_library": (["loan card", "socket set", "extension cord", "return shelf", "safety sheet",
                      "inventory tag"],
                     ["is stamped at checkout", "was returned on time", "hangs behind the desk",
                      "is borrowed for a week", "was wiped and inspected", "is scanned at the door"]),
}

_names = list(THEMES)
SPLITS = {
    "calibration": _names[0:4],
    "dev": _names[4:12],
    "eval": _names[12:44],
    "reversal": _names[44:60],
}
assert len(_names) == 60 and len(SPLITS["eval"]) == 32 and len(SPLITS["reversal"]) == 16


def sentences(theme):
    subjects, predicates = THEMES[theme]
    return [f"The {s} {p}." for s in subjects for p in predicates]
